apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate
  annotations:
    sidecar.istio.io/inject: "false"  
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"  
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=80.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: us-docker.pkg.dev/spinnaker-community/docker/gate:spinnaker-master-latest-validated
        name: gate
        ports:
        - name: traffic-port
          containerPort: 8084
          protocol: TCP
        readinessProbe:
          httpGet:
            # TODO(ezimanyi): we need some way of making this scheme configurable
            # so the health check passes without SSL enabled.
            scheme: HTTPS
            port: traffic-port
            path: /health
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: gate-config-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
        securityContext:
          allowPrivilegeEscalation: false
          
      terminationGracePeriodSeconds: 720
      volumes:
      - name: gate-config-volume
        secret:
          secretName: gate-config
      - name: spinnaker-secrets-volume
        secret:
          secretName: spinnaker-secrets
      securityContext:
        runAsUser: 10111
        runAsGroup: 10111
        runAsNonRoot: true
        fsGroup: 10111
