apiVersion: v1
kind: Service
metadata:
  name: clouddriver
spec:
  ports:
  - name: http-clouddriver
    port: 7002
    protocol: TCP
    targetPort: 7002
  selector:
    app.kubernetes.io/name: clouddriver
    app.kubernetes.io/instance: clouddriver
  type: ClusterIP
