apiVersion: apps/v1
kind: Deployment
metadata:
  name: front50
  annotations:
    sidecar.istio.io/inject: "false"  
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"  
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=80.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: us-docker.pkg.dev/spinnaker-community/docker/front50:spinnaker-master-latest-validated
        name: front50
        ports:
        - name: traffic-port
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /health
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: front50-config-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
        securityContext:
          allowPrivilegeEscalation: false
          
      terminationGracePeriodSeconds: 720
      volumes:
      - name: front50-config-volume
        secret:
          secretName: front50-config
      - name: spinnaker-secrets-volume
        secret:
          secretName: spinnaker-secrets
      securityContext:
        runAsUser: 10111
        runAsGroup: 10111
        runAsNonRoot: true
        fsGroup: 10111
